const EXTENDED_LOCALES = ["ar", "de", "es", "fr", "id", "ja", "ko", "pt", "ru", "tr", "vi"] as const;

type ExtendedLocale = typeof EXTENDED_LOCALES[number];
type TranslationRow = readonly [string, ...string[]];

const STATIC_TRANSLATION_ROWS: TranslationRow[] = [
  ["Add", "إضافة", "Hinzufügen", "Añadir", "Ajouter", "Tambah", "追加", "추가", "Adicionar", "Добавить", "Ekle", "Thêm"],
  ["Add comment", "إضافة تعليق", "Kommentar hinzufügen", "Añadir comentario", "Ajouter un commentaire", "Tambah komentar", "コメントを追加", "댓글 추가", "Adicionar comentário", "Добавить комментарий", "Yorum ekle", "Thêm bình luận"],
  ["Apply crop", "تطبيق القص", "Zuschnitt anwenden", "Aplicar recorte", "Appliquer le rognage", "Terapkan pangkas", "切り抜きを適用", "자르기 적용", "Aplicar recorte", "Применить обрезку", "Kırpmayı uygula", "Áp dụng cắt"],
  ["Attach mobile text menu to selected text", "ربط قائمة النص المحمولة بالنص المحدد", "Mobiles Textmenü an Auswahl anheften", "Vincular el menú móvil al texto seleccionado", "Attacher le menu mobile au texte sélectionné", "Tempelkan menu teks seluler ke teks terpilih", "モバイル文字メニューを選択テキストに表示", "모바일 텍스트 메뉴를 선택한 텍스트에 표시", "Anexar menu móvel ao texto selecionado", "Привязать мобильное меню к выделенному тексту", "Mobil metin menüsünü seçili metne bağla", "Gắn menu văn bản di động vào phần đã chọn"],
  ["Automatically open generated PDF, MD, DOCX, PPTX, PNG, or HTML files.", "فتح ملفات PDF وMD وDOCX وPPTX وPNG وHTML الناتجة تلقائيا.", "Erzeugte PDF-, MD-, DOCX-, PPTX-, PNG- oder HTML-Dateien automatisch öffnen.", "Abrir automáticamente los archivos PDF, MD, DOCX, PPTX, PNG o HTML generados.", "Ouvrir automatiquement les fichiers PDF, MD, DOCX, PPTX, PNG ou HTML générés.", "Buka otomatis file PDF, MD, DOCX, PPTX, PNG, atau HTML yang dibuat.", "生成した PDF、MD、DOCX、PPTX、PNG、HTML を自動で開きます。", "생성된 PDF, MD, DOCX, PPTX, PNG 또는 HTML 파일을 자동으로 엽니다.", "Abrir automaticamente arquivos PDF, MD, DOCX, PPTX, PNG ou HTML gerados.", "Автоматически открывать созданные PDF, MD, DOCX, PPTX, PNG или HTML.", "Oluşturulan PDF, MD, DOCX, PPTX, PNG veya HTML dosyalarını otomatik aç.", "Tự động mở tệp PDF, MD, DOCX, PPTX, PNG hoặc HTML đã tạo."],
  ["Boost PDF top menu", "تعزيز قائمة PDF العلوية", "PDF-Menü oben verstärken", "Mejorar menú superior de PDF", "Renforcer le menu PDF supérieur", "Perkuat menu atas PDF", "PDF 上部メニューを強化", "PDF 상단 메뉴 강화", "Reforçar menu superior do PDF", "Усилить верхнее меню PDF", "PDF üst menüsünü güçlendir", "Tăng cường menu trên PDF"],
  ["Bottom", "أسفل", "Unten", "Abajo", "Bas", "Bawah", "下", "아래", "Inferior", "Снизу", "Alt", "Dưới"],
  ["Bring to front", "إحضار إلى الأمام", "In den Vordergrund", "Traer al frente", "Mettre au premier plan", "Bawa ke depan", "最前面へ", "맨 앞으로", "Trazer para frente", "На передний план", "En öne getir", "Đưa lên trước"],
  ["Cannot delete all pages.", "لا يمكن حذف كل الصفحات.", "Es können nicht alle Seiten gelöscht werden.", "No se pueden eliminar todas las páginas.", "Impossible de supprimer toutes les pages.", "Tidak dapat menghapus semua halaman.", "すべてのページは削除できません。", "모든 페이지를 삭제할 수 없습니다.", "Não é possível excluir todas as páginas.", "Нельзя удалить все страницы.", "Tüm sayfalar silinemez.", "Không thể xóa tất cả trang."],
  ["Capture image", "التقاط صورة", "Bild erfassen", "Capturar imagen", "Capturer une image", "Ambil gambar", "画像を切り出す", "이미지 캡처", "Capturar imagem", "Захватить изображение", "Görüntü yakala", "Chụp ảnh"],
  ["Clear", "مسح", "Leeren", "Limpiar", "Effacer", "Bersihkan", "クリア", "지우기", "Limpar", "Очистить", "Temizle", "Xóa"],
  ["Clear annotations", "مسح التعليقات", "Anmerkungen löschen", "Borrar anotaciones", "Effacer les annotations", "Bersihkan anotasi", "注釈を消去", "주석 지우기", "Limpar anotações", "Очистить аннотации", "Notları temizle", "Xóa chú thích"],
  ["Clear editable annotations? This will not delete original PDF content, but it will remove overlays and plugin annotations.", "مسح التعليقات القابلة للتحرير؟ لن يحذف ذلك محتوى PDF الأصلي، لكنه سيزيل الطبقات وتعليقات الإضافة.", "Bearbeitbare Anmerkungen löschen? Der PDF-Inhalt bleibt erhalten, aber Überlagerungen und Plugin-Anmerkungen werden entfernt.", "¿Borrar anotaciones editables? No se eliminará el PDF original, pero sí las capas y anotaciones del complemento.", "Effacer les annotations modifiables ? Le PDF original restera intact, mais les calques et annotations du module seront supprimés.", "Hapus anotasi yang dapat diedit? Isi PDF asli tetap ada, tetapi overlay dan anotasi plugin akan dihapus.", "編集可能な注釈を消去しますか？元の PDF 内容は残りますが、オーバーレイとプラグイン注釈は削除されます。", "편집 가능한 주석을 지울까요? 원본 PDF 내용은 유지되지만 오버레이와 플러그인 주석은 제거됩니다.", "Limpar anotações editáveis? O PDF original será mantido, mas sobreposições e anotações do plugin serão removidas.", "Очистить редактируемые аннотации? Исходный PDF сохранится, но наложения и аннотации плагина будут удалены.", "Düzenlenebilir notlar temizlensin mi? Özgün PDF içeriği kalır, ancak katmanlar ve eklenti notları kaldırılır.", "Xóa chú thích có thể chỉnh sửa? Nội dung PDF gốc vẫn giữ nguyên, nhưng lớp phủ và chú thích plugin sẽ bị xóa."],
  ["Click the page to add a comment.", "انقر الصفحة لإضافة تعليق.", "Auf die Seite klicken, um einen Kommentar hinzuzufügen.", "Haz clic en la página para añadir un comentario.", "Cliquez sur la page pour ajouter un commentaire.", "Klik halaman untuk menambah komentar.", "ページをクリックしてコメントを追加します。", "페이지를 클릭해 댓글을 추가하세요.", "Clique na página para adicionar um comentário.", "Щёлкните страницу, чтобы добавить комментарий.", "Yorum eklemek için sayfaya tıklayın.", "Nhấp vào trang để thêm bình luận."],
  ["Comment", "تعليق", "Kommentar", "Comentario", "Commentaire", "Komentar", "コメント", "댓글", "Comentário", "Комментарий", "Yorum", "Bình luận"],
  ["Comment manager", "مدير التعليقات", "Kommentarverwaltung", "Gestor de comentarios", "Gestionnaire de commentaires", "Pengelola komentar", "コメント管理", "댓글 관리자", "Gerenciador de comentários", "Управление комментариями", "Yorum yöneticisi", "Quản lý bình luận"],
  ["Could not auto-save into this PDF. Check the console for details.", "تعذر الحفظ التلقائي في ملف PDF. راجع وحدة التحكم للتفاصيل.", "Automatisches Speichern in dieses PDF fehlgeschlagen. Details in der Konsole.", "No se pudo guardar automáticamente en este PDF. Revisa la consola.", "Enregistrement automatique dans ce PDF impossible. Consultez la console.", "Gagal menyimpan otomatis ke PDF ini. Periksa konsol.", "この PDF に自動保存できませんでした。詳細はコンソールを確認してください。", "이 PDF에 자동 저장하지 못했습니다. 콘솔에서 세부 정보를 확인하세요.", "Não foi possível salvar automaticamente neste PDF. Verifique o console.", "Не удалось автоматически сохранить в PDF. Подробности в консоли.", "Bu PDF'ye otomatik kaydedilemedi. Ayrıntılar için konsolu kontrol edin.", "Không thể tự động lưu vào PDF này. Xem bảng điều khiển để biết chi tiết."],
  ["Could not revert. Check the console.", "تعذر التراجع. راجع وحدة التحكم.", "Wiederherstellung fehlgeschlagen. Konsole prüfen.", "No se pudo revertir. Revisa la consola.", "Restauration impossible. Consultez la console.", "Gagal mengembalikan. Periksa konsol.", "元に戻せませんでした。コンソールを確認してください。", "되돌리지 못했습니다. 콘솔을 확인하세요.", "Não foi possível reverter. Verifique o console.", "Не удалось восстановить. Проверьте консоль.", "Geri alınamadı. Konsolu kontrol edin.", "Không thể hoàn tác. Hãy kiểm tra bảng điều khiển."],
  ["Crop pages", "قص الصفحات", "Seiten zuschneiden", "Recortar páginas", "Rogner les pages", "Pangkas halaman", "ページを切り抜く", "페이지 자르기", "Recortar páginas", "Обрезать страницы", "Sayfaları kırp", "Cắt trang"],
  ["DOCX conversion failed. Check the console.", "فشل تحويل DOCX. راجع وحدة التحكم.", "DOCX-Konvertierung fehlgeschlagen. Konsole prüfen.", "Falló la conversión DOCX. Revisa la consola.", "Échec de la conversion DOCX. Consultez la console.", "Konversi DOCX gagal. Periksa konsol.", "DOCX 変換に失敗しました。コンソールを確認してください。", "DOCX 변환에 실패했습니다. 콘솔을 확인하세요.", "Falha na conversão DOCX. Verifique o console.", "Ошибка преобразования DOCX. Проверьте консоль.", "DOCX dönüştürme başarısız. Konsolu kontrol edin.", "Chuyển đổi DOCX thất bại. Hãy kiểm tra bảng điều khiển."],
  ["Data and AI", "البيانات والذكاء الاصطناعي", "Daten und KI", "Datos e IA", "Données et IA", "Data dan AI", "データと AI", "데이터 및 AI", "Dados e IA", "Данные и ИИ", "Veri ve yapay zeka", "Dữ liệu và AI"],
  ["Delete", "حذف", "Löschen", "Eliminar", "Supprimer", "Hapus", "削除", "삭제", "Excluir", "Удалить", "Sil", "Xóa"],
  ["Delete comment", "حذف التعليق", "Kommentar löschen", "Eliminar comentario", "Supprimer le commentaire", "Hapus komentar", "コメントを削除", "댓글 삭제", "Excluir comentário", "Удалить комментарий", "Yorumu sil", "Xóa bình luận"],
  ["Drag a PDF region to capture it as an editable image.", "اسحب منطقة من PDF لالتقاطها كصورة قابلة للتحرير.", "Einen PDF-Bereich ziehen, um ihn als bearbeitbares Bild zu erfassen.", "Arrastra una región del PDF para capturarla como imagen editable.", "Faites glisser une zone du PDF pour la capturer comme image modifiable.", "Seret area PDF untuk menangkapnya sebagai gambar yang dapat diedit.", "PDF の範囲をドラッグして編集可能な画像として取り込みます。", "PDF 영역을 드래그해 편집 가능한 이미지로 캡처하세요.", "Arraste uma região do PDF para capturá-la como imagem editável.", "Выделите область PDF, чтобы захватить её как редактируемое изображение.", "Düzenlenebilir görüntü olarak yakalamak için PDF bölgesini sürükleyin.", "Kéo một vùng PDF để chụp thành ảnh có thể chỉnh sửa."],
  ["Edit comment", "تحرير التعليق", "Kommentar bearbeiten", "Editar comentario", "Modifier le commentaire", "Edit komentar", "コメントを編集", "댓글 편집", "Editar comentário", "Изменить комментарий", "Yorumu düzenle", "Sửa bình luận"],
  ["Edit the comment content.", "حرر محتوى التعليق.", "Kommentarinhalt bearbeiten.", "Edita el contenido del comentario.", "Modifiez le contenu du commentaire.", "Edit isi komentar.", "コメント内容を編集します。", "댓글 내용을 편집하세요.", "Edite o conteúdo do comentário.", "Измените текст комментария.", "Yorum içeriğini düzenleyin.", "Sửa nội dung bình luận."],
  ["Element layer", "طبقة العنصر", "Elementebene", "Capa del elemento", "Calque de l'élément", "Lapisan elemen", "要素レイヤー", "요소 레이어", "Camada do elemento", "Слой элемента", "Öğe katmanı", "Lớp phần tử"],
  ["Enter a link or note name, for example [[Note]] / ![[image.png]]", "أدخل رابطا أو اسم ملاحظة، مثل [[Note]] / ![[image.png]]", "Link oder Notiznamen eingeben, z. B. [[Note]] / ![[image.png]]", "Introduce un enlace o nombre de nota, por ejemplo [[Note]] / ![[image.png]]", "Saisissez un lien ou un nom de note, par exemple [[Note]] / ![[image.png]]", "Masukkan tautan atau nama catatan, misalnya [[Note]] / ![[image.png]]", "リンクまたはノート名を入力します。例: [[Note]] / ![[image.png]]", "링크 또는 노트 이름을 입력하세요. 예: [[Note]] / ![[image.png]]", "Digite um link ou nome de nota, por exemplo [[Note]] / ![[image.png]]", "Введите ссылку или имя заметки, например [[Note]] / ![[image.png]]", "Bir bağlantı veya not adı girin, örneğin [[Note]] / ![[image.png]]", "Nhập liên kết hoặc tên ghi chú, ví dụ [[Note]] / ![[image.png]]"],
  ["Enter left, top, right, and bottom margins separately. Use 0.05 or 5%. Preview lines update as you type.", "أدخل هوامش اليسار والأعلى واليمين والأسفل منفصلة. استخدم 0.05 أو 5%. تتحدث خطوط المعاينة أثناء الكتابة.", "Linken, oberen, rechten und unteren Rand getrennt eingeben. 0,05 oder 5 % verwenden. Die Vorschau wird sofort aktualisiert.", "Introduce por separado los márgenes izquierdo, superior, derecho e inferior. Usa 0,05 o 5 %. La vista previa se actualiza al escribir.", "Saisissez séparément les marges gauche, haute, droite et basse. Utilisez 0,05 ou 5 %. L'aperçu se met à jour pendant la saisie.", "Masukkan margin kiri, atas, kanan, dan bawah secara terpisah. Gunakan 0,05 atau 5%. Pratinjau diperbarui saat mengetik.", "左、上、右、下の余白を個別に入力します。0.05 または 5% を使用でき、入力中にプレビューが更新されます。", "왼쪽, 위, 오른쪽, 아래 여백을 각각 입력하세요. 0.05 또는 5%를 사용할 수 있으며 입력 중 미리보기가 갱신됩니다.", "Digite separadamente as margens esquerda, superior, direita e inferior. Use 0,05 ou 5%. A prévia é atualizada ao digitar.", "Введите отдельно левое, верхнее, правое и нижнее поля. Используйте 0,05 или 5 %. Предпросмотр обновляется при вводе.", "Sol, üst, sağ ve alt kenarları ayrı girin. 0,05 veya %5 kullanın. Önizleme yazarken güncellenir.", "Nhập riêng lề trái, trên, phải và dưới. Dùng 0,05 hoặc 5%. Đường xem trước cập nhật khi nhập."],
  ["Enter the comment content.", "أدخل محتوى التعليق.", "Kommentarinhalt eingeben.", "Introduce el contenido del comentario.", "Saisissez le contenu du commentaire.", "Masukkan isi komentar.", "コメント内容を入力します。", "댓글 내용을 입력하세요.", "Digite o conteúdo do comentário.", "Введите текст комментария.", "Yorum içeriğini girin.", "Nhập nội dung bình luận."],
  ["Export", "تصدير", "Exportieren", "Exportar", "Exporter", "Ekspor", "エクスポート", "내보내기", "Exportar", "Экспорт", "Dışa aktar", "Xuất"],
  ["Export HTML", "تصدير HTML", "HTML exportieren", "Exportar HTML", "Exporter HTML", "Ekspor HTML", "HTML 出力", "HTML 내보내기", "Exportar HTML", "Экспорт HTML", "HTML dışa aktar", "Xuất HTML"],
  ["Export PNG", "تصدير PNG", "PNG exportieren", "Exportar PNG", "Exporter PNG", "Ekspor PNG", "PNG 出力", "PNG 내보내기", "Exportar PNG", "Экспорт PNG", "PNG dışa aktar", "Xuất PNG"],
  ["Export PPTX", "تصدير PPTX", "PPTX exportieren", "Exportar PPTX", "Exporter PPTX", "Ekspor PPTX", "PPTX 出力", "PPTX 내보내기", "Exportar PPTX", "Экспорт PPTX", "PPTX dışa aktar", "Xuất PPTX"],
  ["Export annotations to DOCX", "تصدير التعليقات إلى DOCX", "Anmerkungen als DOCX exportieren", "Exportar anotaciones a DOCX", "Exporter les annotations vers DOCX", "Ekspor anotasi ke DOCX", "注釈を DOCX に出力", "주석을 DOCX로 내보내기", "Exportar anotações para DOCX", "Экспорт аннотаций в DOCX", "Notları DOCX'e aktar", "Xuất chú thích sang DOCX"],
  ["Export annotations to Markdown", "تصدير التعليقات إلى Markdown", "Anmerkungen als Markdown exportieren", "Exportar anotaciones a Markdown", "Exporter les annotations vers Markdown", "Ekspor anotasi ke Markdown", "注釈を Markdown に出力", "주석을 Markdown으로 내보내기", "Exportar anotações para Markdown", "Экспорт аннотаций в Markdown", "Notları Markdown'a aktar", "Xuất chú thích sang Markdown"],
  ["Export annotations to PPTX", "تصدير التعليقات إلى PPTX", "Anmerkungen als PPTX exportieren", "Exportar anotaciones a PPTX", "Exporter les annotations vers PPTX", "Ekspor anotasi ke PPTX", "注釈を PPTX に出力", "주석을 PPTX로 내보내기", "Exportar anotações para PPTX", "Экспорт аннотаций в PPTX", "Notları PPTX'e aktar", "Xuất chú thích sang PPTX"],
  ["Export visible annotated PDF", "تصدير PDF المرئي مع التعليقات", "Sichtbares PDF mit Anmerkungen exportieren", "Exportar PDF visible con anotaciones", "Exporter le PDF visible annoté", "Ekspor PDF terlihat dengan anotasi", "表示中の注釈付き PDF を出力", "보이는 주석 PDF 내보내기", "Exportar PDF visível anotado", "Экспорт видимого PDF с аннотациями", "Görünen açıklamalı PDF'yi dışa aktar", "Xuất PDF chú thích đang hiển thị"],
  ["Exporting burned-in PDF...", "جار تصدير PDF مدمج التعليقات...", "PDF mit eingebrannten Anmerkungen wird exportiert...", "Exportando PDF con anotaciones integradas...", "Export du PDF avec annotations intégrées...", "Mengekspor PDF dengan anotasi tertanam...", "注釈を焼き込んだ PDF を出力中...", "주석이 포함된 PDF 내보내는 중...", "Exportando PDF com anotações incorporadas...", "Экспорт PDF со встроенными аннотациями...", "Notlar gömülü PDF dışa aktarılıyor...", "Đang xuất PDF có chú thích được nhúng..."],
  ["Flatten", "تسطيح", "Reduzieren", "Acoplar", "Aplatir", "Ratakan", "統合", "병합", "Achatar", "Свести", "Düzleştir", "Làm phẳng"],
  ["Flatten covers", "تسطيح مناطق التغطية", "Abdeckungen reduzieren", "Acoplar cubiertas", "Aplatir les caches", "Ratakan penutup", "覆いを統合", "가림 영역 병합", "Achatar coberturas", "Свести закрывающие области", "Kapakları düzleştir", "Làm phẳng vùng che"],
  ["Flattening covers will modify the current PDF by rebuilding rendered covered pages as images. Continue?", "سيؤدي تسطيح مناطق التغطية إلى تعديل PDF الحالي بإعادة بناء الصفحات المغطاة كصور. هل تريد المتابعة؟", "Das Reduzieren der Abdeckungen ändert das aktuelle PDF, indem betroffene Seiten als Bilder neu aufgebaut werden. Fortfahren?", "Acoplar las cubiertas modificará el PDF actual reconstruyendo como imágenes las páginas cubiertas. ¿Continuar?", "L'aplatissement des caches modifiera le PDF actuel en reconstruisant les pages concernées sous forme d'images. Continuer ?", "Meratakan penutup akan mengubah PDF saat ini dengan membangun ulang halaman tertutup sebagai gambar. Lanjutkan?", "覆いを統合すると、対象ページを画像として再構築し、現在の PDF を変更します。続行しますか？", "가림 영역을 병합하면 해당 페이지를 이미지로 다시 만들어 현재 PDF가 수정됩니다. 계속할까요?", "Achatar as coberturas modificará o PDF atual, reconstruindo as páginas cobertas como imagens. Continuar?", "Сведение закрывающих областей изменит текущий PDF, пересоздав затронутые страницы как изображения. Продолжить?", "Kapakları düzleştirmek, kapalı sayfaları görüntü olarak yeniden oluşturarak mevcut PDF'yi değiştirir. Devam edilsin mi?", "Làm phẳng vùng che sẽ sửa PDF hiện tại bằng cách dựng lại các trang bị che thành ảnh. Tiếp tục?"],
  ["HTML conversion failed. Check the console.", "فشل تحويل HTML. راجع وحدة التحكم.", "HTML-Konvertierung fehlgeschlagen. Konsole prüfen.", "Falló la conversión HTML. Revisa la consola.", "Échec de la conversion HTML. Consultez la console.", "Konversi HTML gagal. Periksa konsol.", "HTML 変換に失敗しました。コンソールを確認してください。", "HTML 변환에 실패했습니다. 콘솔을 확인하세요.", "Falha na conversão HTML. Verifique o console.", "Ошибка преобразования HTML. Проверьте консоль.", "HTML dönüştürme başarısız. Konsolu kontrol edin.", "Chuyển đổi HTML thất bại. Hãy kiểm tra bảng điều khiển."],
  ["Image could not be loaded", "تعذر تحميل الصورة", "Bild konnte nicht geladen werden", "No se pudo cargar la imagen", "Impossible de charger l'image", "Gambar tidak dapat dimuat", "画像を読み込めませんでした", "이미지를 불러올 수 없습니다", "Não foi possível carregar a imagem", "Не удалось загрузить изображение", "Görüntü yüklenemedi", "Không thể tải ảnh"],
  ["Insert", "إدراج", "Einfügen", "Insertar", "Insérer", "Sisipkan", "挿入", "삽입", "Inserir", "Вставить", "Ekle", "Chèn"],
  ["Insert after which page? Use 0 for the beginning, or leave blank to insert after the selected page.", "بعد أي صفحة تريد الإدراج؟ استخدم 0 للبداية، أو اتركه فارغا للإدراج بعد الصفحة المحددة.", "Nach welcher Seite einfügen? 0 für den Anfang verwenden oder leer lassen, um nach der ausgewählten Seite einzufügen.", "¿Después de qué página? Usa 0 para el inicio o déjalo vacío para insertar después de la página seleccionada.", "Après quelle page insérer ? Utilisez 0 pour le début ou laissez vide pour insérer après la page sélectionnée.", "Sisipkan setelah halaman mana? Gunakan 0 untuk awal, atau kosongkan untuk menyisipkan setelah halaman terpilih.", "どのページの後に挿入しますか？先頭は 0、選択ページの後なら空欄にします。", "어느 페이지 뒤에 삽입할까요? 맨 앞은 0, 선택한 페이지 뒤는 빈칸으로 두세요.", "Inserir depois de qual página? Use 0 para o início ou deixe em branco para inserir após a página selecionada.", "После какой страницы вставить? Введите 0 для начала или оставьте пустым для вставки после выбранной страницы.", "Hangi sayfadan sonra eklensin? Başlangıç için 0 kullanın veya seçili sayfadan sonrası için boş bırakın.", "Chèn sau trang nào? Dùng 0 để chèn đầu tài liệu hoặc để trống để chèn sau trang đã chọn."],
  ["Invalid crop values. Margins cannot remove the whole page.", "قيم القص غير صالحة. لا يمكن للهوامش إزالة الصفحة كلها.", "Ungültige Zuschnittwerte. Die Ränder dürfen nicht die ganze Seite entfernen.", "Valores de recorte no válidos. Los márgenes no pueden eliminar toda la página.", "Valeurs de rognage incorrectes. Les marges ne peuvent pas supprimer toute la page.", "Nilai pangkas tidak valid. Margin tidak boleh menghapus seluruh halaman.", "切り抜き値が無効です。ページ全体を消す余白にはできません。", "자르기 값이 잘못되었습니다. 여백으로 전체 페이지를 제거할 수 없습니다.", "Valores de recorte inválidos. As margens não podem remover a página inteira.", "Недопустимые параметры обрезки. Поля не могут удалить всю страницу.", "Kırpma değerleri geçersiz. Kenarlar tüm sayfayı kaldıramaz.", "Giá trị cắt không hợp lệ. Lề không thể loại bỏ toàn bộ trang."],
  ["Invalid page order.", "ترتيب الصفحات غير صالح.", "Ungültige Seitenreihenfolge.", "Orden de páginas no válido.", "Ordre des pages incorrect.", "Urutan halaman tidak valid.", "ページ順が無効です。", "페이지 순서가 잘못되었습니다.", "Ordem de páginas inválida.", "Недопустимый порядок страниц.", "Sayfa sırası geçersiz.", "Thứ tự trang không hợp lệ."],
  ["Left", "يسار", "Links", "Izquierda", "Gauche", "Kiri", "左", "왼쪽", "Esquerda", "Слева", "Sol", "Trái"],
  ["MD conversion failed. Check the console.", "فشل تحويل MD. راجع وحدة التحكم.", "MD-Konvertierung fehlgeschlagen. Konsole prüfen.", "Falló la conversión MD. Revisa la consola.", "Échec de la conversion MD. Consultez la console.", "Konversi MD gagal. Periksa konsol.", "MD 変換に失敗しました。コンソールを確認してください。", "MD 변환에 실패했습니다. 콘솔을 확인하세요.", "Falha na conversão MD. Verifique o console.", "Ошибка преобразования MD. Проверьте консоль.", "MD dönüştürme başarısız. Konsolu kontrol edin.", "Chuyển đổi MD thất bại. Hãy kiểm tra bảng điều khiển."],
  ["Move down", "تحريك لأسفل", "Nach unten", "Mover abajo", "Descendre", "Turunkan", "下へ移動", "아래로 이동", "Mover para baixo", "Переместить вниз", "Aşağı taşı", "Di chuyển xuống"],
  ["Move one layer down", "تحريك طبقة واحدة لأسفل", "Eine Ebene nach unten", "Bajar una capa", "Descendre d'un calque", "Turun satu lapisan", "1 レイヤー下へ", "한 레이어 아래로", "Descer uma camada", "На слой ниже", "Bir katman aşağı", "Xuống một lớp"],
  ["Move one layer up", "تحريك طبقة واحدة لأعلى", "Eine Ebene nach oben", "Subir una capa", "Monter d'un calque", "Naik satu lapisan", "1 レイヤー上へ", "한 레이어 위로", "Subir uma camada", "На слой выше", "Bir katman yukarı", "Lên một lớp"],
  ["Move up", "تحريك لأعلى", "Nach oben", "Mover arriba", "Monter", "Naikkan", "上へ移動", "위로 이동", "Mover para cima", "Переместить вверх", "Yukarı taşı", "Di chuyển lên"],
  ["No PDF page is available for image insertion.", "لا توجد صفحة PDF متاحة لإدراج الصورة.", "Keine PDF-Seite zum Einfügen eines Bildes verfügbar.", "No hay una página PDF disponible para insertar la imagen.", "Aucune page PDF n'est disponible pour insérer l'image.", "Tidak ada halaman PDF untuk menyisipkan gambar.", "画像を挿入できる PDF ページがありません。", "이미지를 삽입할 PDF 페이지가 없습니다.", "Não há página PDF disponível para inserir a imagem.", "Нет страницы PDF для вставки изображения.", "Görüntü eklemek için PDF sayfası yok.", "Không có trang PDF để chèn ảnh."],
  ["No PDF page is available for link insertion.", "لا توجد صفحة PDF متاحة لإدراج الرابط.", "Keine PDF-Seite zum Einfügen eines Links verfügbar.", "No hay una página PDF disponible para insertar el enlace.", "Aucune page PDF n'est disponible pour insérer le lien.", "Tidak ada halaman PDF untuk menyisipkan tautan.", "リンクを挿入できる PDF ページがありません。", "링크를 삽입할 PDF 페이지가 없습니다.", "Não há página PDF disponível para inserir o link.", "Нет страницы PDF для вставки ссылки.", "Bağlantı eklemek için PDF sayfası yok.", "Không có trang PDF để chèn liên kết."],
  ["No PDF rewrite backup is available.", "لا توجد نسخة احتياطية لإعادة كتابة PDF.", "Keine Sicherung vor der PDF-Neuschreibung verfügbar.", "No hay copia de seguridad de la reescritura del PDF.", "Aucune sauvegarde de réécriture du PDF n'est disponible.", "Tidak ada cadangan penulisan ulang PDF.", "PDF 書き換え前のバックアップがありません。", "PDF 다시 쓰기 백업이 없습니다.", "Não há backup da regravação do PDF.", "Нет резервной копии до перезаписи PDF.", "PDF yeniden yazma yedeği yok.", "Không có bản sao lưu trước khi ghi lại PDF."],
  ["No comments", "لا توجد تعليقات", "Keine Kommentare", "Sin comentarios", "Aucun commentaire", "Tidak ada komentar", "コメントなし", "댓글 없음", "Sem comentários", "Нет комментариев", "Yorum yok", "Không có bình luận"],
  ["No cover regions to flatten.", "لا توجد مناطق تغطية لتسطيحها.", "Keine Abdeckbereiche zum Reduzieren.", "No hay regiones cubiertas para acoplar.", "Aucune zone masquée à aplatir.", "Tidak ada area penutup untuk diratakan.", "統合する覆い領域がありません。", "병합할 가림 영역이 없습니다.", "Não há regiões de cobertura para achatar.", "Нет закрывающих областей для сведения.", "Düzleştirilecek kapak alanı yok.", "Không có vùng che để làm phẳng."],
  ["No highlight", "بدون تمييز", "Keine Markierung", "Sin resaltado", "Sans surlignage", "Tanpa sorotan", "ハイライトなし", "하이라이트 없음", "Sem destaque", "Без подсветки", "Vurgusuz", "Không tô sáng"],
  ["No image configured", "لم يتم إعداد صورة", "Kein Bild konfiguriert", "No hay imagen configurada", "Aucune image configurée", "Tidak ada gambar yang dikonfigurasi", "画像が設定されていません", "설정된 이미지 없음", "Nenhuma imagem configurada", "Изображение не настроено", "Görüntü ayarlanmadı", "Chưa cấu hình ảnh"],
  ["No insertable image was found.", "لم يتم العثور على صورة قابلة للإدراج.", "Kein einfügbares Bild gefunden.", "No se encontró una imagen insertable.", "Aucune image insérable trouvée.", "Tidak ditemukan gambar yang dapat disisipkan.", "挿入できる画像が見つかりません。", "삽입할 수 있는 이미지를 찾지 못했습니다.", "Nenhuma imagem inserível foi encontrada.", "Не найдено изображение для вставки.", "Eklenebilir görüntü bulunamadı.", "Không tìm thấy ảnh có thể chèn."],
  ["No new annotations to save.", "لا توجد تعليقات جديدة للحفظ.", "Keine neuen Anmerkungen zu speichern.", "No hay anotaciones nuevas que guardar.", "Aucune nouvelle annotation à enregistrer.", "Tidak ada anotasi baru untuk disimpan.", "保存する新しい注釈はありません。", "저장할 새 주석이 없습니다.", "Não há novas anotações para salvar.", "Нет новых аннотаций для сохранения.", "Kaydedilecek yeni not yok.", "Không có chú thích mới để lưu."],
  ["No rendered covered pages are available. Scroll to covered pages and try again.", "لا توجد صفحات مغطاة معروضة. انتقل إلى الصفحات المغطاة وحاول مجددا.", "Keine gerenderten abgedeckten Seiten verfügbar. Zu den Seiten scrollen und erneut versuchen.", "No hay páginas cubiertas renderizadas. Desplázate hasta ellas e inténtalo de nuevo.", "Aucune page masquée rendue n'est disponible. Faites défiler jusqu'aux pages concernées et réessayez.", "Tidak ada halaman tertutup yang sudah dirender. Gulir ke halaman tersebut lalu coba lagi.", "描画済みの覆いページがありません。対象ページまでスクロールして再試行してください。", "렌더링된 가림 페이지가 없습니다. 해당 페이지로 스크롤한 뒤 다시 시도하세요.", "Não há páginas cobertas renderizadas. Role até elas e tente novamente.", "Нет отрисованных закрытых страниц. Прокрутите к ним и повторите попытку.", "İşlenmiş kapalı sayfa yok. Kapalı sayfalara kaydırıp yeniden deneyin.", "Không có trang bị che đã kết xuất. Cuộn đến các trang đó rồi thử lại."],
  ["Open after export", "الفتح بعد التصدير", "Nach Export öffnen", "Abrir después de exportar", "Ouvrir après l'export", "Buka setelah ekspor", "出力後に開く", "내보낸 후 열기", "Abrir após exportar", "Открывать после экспорта", "Dışa aktardıktan sonra aç", "Mở sau khi xuất"],
  ["PDF link", "رابط PDF", "PDF-Link", "Enlace PDF", "Lien PDF", "Tautan PDF", "PDF リンク", "PDF 링크", "Link PDF", "Ссылка PDF", "PDF bağlantısı", "Liên kết PDF"],
  ["PDF text", "نص PDF", "PDF-Text", "Texto PDF", "Texte PDF", "Teks PDF", "PDF テキスト", "PDF 텍스트", "Texto PDF", "Текст PDF", "PDF metni", "Văn bản PDF"],
  ["PDF/Markdown/DOCX conversion", "تحويل PDF/Markdown/DOCX", "PDF/Markdown/DOCX-Konvertierung", "Conversión PDF/Markdown/DOCX", "Conversion PDF/Markdown/DOCX", "Konversi PDF/Markdown/DOCX", "PDF/Markdown/DOCX 変換", "PDF/Markdown/DOCX 변환", "Conversão PDF/Markdown/DOCX", "Преобразование PDF/Markdown/DOCX", "PDF/Markdown/DOCX dönüştürme", "Chuyển đổi PDF/Markdown/DOCX"],
  ["PNG conversion failed. Check the console.", "فشل تحويل PNG. راجع وحدة التحكم.", "PNG-Konvertierung fehlgeschlagen. Konsole prüfen.", "Falló la conversión PNG. Revisa la consola.", "Échec de la conversion PNG. Consultez la console.", "Konversi PNG gagal. Periksa konsol.", "PNG 変換に失敗しました。コンソールを確認してください。", "PNG 변환에 실패했습니다. 콘솔을 확인하세요.", "Falha na conversão PNG. Verifique o console.", "Ошибка преобразования PNG. Проверьте консоль.", "PNG dönüştürme başarısız. Konsolu kontrol edin.", "Chuyển đổi PNG thất bại. Hãy kiểm tra bảng điều khiển."],
  ["Page crop values recorded.", "تم تسجيل قيم قص الصفحة.", "Seitenzuschnitt gespeichert.", "Valores de recorte registrados.", "Valeurs de rognage enregistrées.", "Nilai pangkas halaman dicatat.", "ページの切り抜き値を記録しました。", "페이지 자르기 값을 기록했습니다.", "Valores de recorte registrados.", "Параметры обрезки страницы сохранены.", "Sayfa kırpma değerleri kaydedildi.", "Đã ghi giá trị cắt trang."],
  ["Pages deleted", "تم حذف الصفحات", "Seiten gelöscht", "Páginas eliminadas", "Pages supprimées", "Halaman dihapus", "ページを削除しました", "페이지 삭제됨", "Páginas excluídas", "Страницы удалены", "Sayfalar silindi", "Đã xóa trang"],
  ["Pages reordered", "تمت إعادة ترتيب الصفحات", "Seiten neu angeordnet", "Páginas reordenadas", "Pages réordonnées", "Halaman disusun ulang", "ページを並べ替えました", "페이지 순서 변경됨", "Páginas reordenadas", "Порядок страниц изменён", "Sayfalar yeniden sıralandı", "Đã sắp xếp lại trang"],
  ["Payment QR", "رمز QR للدفع", "Zahlungs-QR", "QR de pago", "QR de paiement", "QR pembayaran", "支払い QR", "결제 QR", "QR de pagamento", "QR для оплаты", "Ödeme QR", "QR thanh toán"],
  ["Pdftion auto-saves editable annotation data and exposes PdftionAI / __PDftionAI__ on the window for local scripts or AI agents to inspect, summarize, and operate the active PDF annotations.", "يحفظ Pdftion بيانات التعليقات القابلة للتحرير تلقائيا، ويعرض PdftionAI / __PDftionAI__ للنصوص المحلية أو وكلاء الذكاء الاصطناعي لفحص تعليقات PDF النشطة وتلخيصها وتشغيلها.", "Pdftion speichert bearbeitbare Anmerkungen automatisch und stellt PdftionAI / __PDftionAI__ im Fenster bereit, damit lokale Skripte oder KI-Agenten aktive PDF-Anmerkungen prüfen, zusammenfassen und bedienen können.", "Pdftion guarda automáticamente las anotaciones editables y expone PdftionAI / __PDftionAI__ en la ventana para que scripts locales o agentes de IA inspeccionen, resuman y operen las anotaciones PDF activas.", "Pdftion enregistre automatiquement les annotations modifiables et expose PdftionAI / __PDftionAI__ dans la fenêtre afin que les scripts locaux ou agents IA puissent inspecter, résumer et manipuler les annotations PDF actives.", "Pdftion menyimpan otomatis data anotasi yang dapat diedit dan mengekspos PdftionAI / __PDftionAI__ agar skrip lokal atau agen AI dapat memeriksa, merangkum, dan mengoperasikan anotasi PDF aktif.", "Pdftion は編集可能な注釈データを自動保存し、ローカルスクリプトや AI エージェントが現在の PDF 注釈を確認、要約、操作できるよう PdftionAI / __PDftionAI__ を公開します。", "Pdftion은 편집 가능한 주석 데이터를 자동 저장하고 로컬 스크립트나 AI 에이전트가 활성 PDF 주석을 검사, 요약, 조작할 수 있도록 PdftionAI / __PDftionAI__를 제공합니다.", "O Pdftion salva automaticamente os dados de anotações editáveis e expõe PdftionAI / __PDftionAI__ para scripts locais ou agentes de IA inspecionarem, resumirem e operarem as anotações PDF ativas.", "Pdftion автоматически сохраняет редактируемые аннотации и предоставляет PdftionAI / __PDftionAI__, чтобы локальные скрипты или ИИ-агенты могли проверять, суммировать и изменять активные аннотации PDF.", "Pdftion düzenlenebilir not verilerini otomatik kaydeder ve yerel betiklerin veya yapay zeka ajanlarının etkin PDF notlarını incelemesi, özetlemesi ve işlemesi için PdftionAI / __PDftionAI__ sunar.", "Pdftion tự động lưu dữ liệu chú thích có thể chỉnh sửa và cung cấp PdftionAI / __PDftionAI__ để tập lệnh cục bộ hoặc tác nhân AI kiểm tra, tóm tắt và thao tác chú thích PDF đang hoạt động."],
  ["Pdftion settings", "إعدادات Pdftion", "Pdftion-Einstellungen", "Ajustes de Pdftion", "Paramètres de Pdftion", "Pengaturan Pdftion", "Pdftion 設定", "Pdftion 설정", "Configurações do Pdftion", "Настройки Pdftion", "Pdftion ayarları", "Cài đặt Pdftion"],
  ["Pixels. 22-32 is recommended; use larger values on touch screens.", "بالبكسل. يوصى بـ 22-32؛ استخدم قيما أكبر على شاشات اللمس.", "Pixel. 22–32 wird empfohlen; auf Touchscreens größere Werte verwenden.", "Píxeles. Se recomienda 22-32; usa valores mayores en pantallas táctiles.", "Pixels. 22 à 32 est recommandé ; utilisez une valeur supérieure sur écran tactile.", "Piksel. Disarankan 22-32; gunakan nilai lebih besar pada layar sentuh.", "ピクセル。22～32 を推奨し、タッチ画面では大きめにします。", "픽셀. 22~32를 권장하며 터치 화면에서는 더 큰 값을 사용하세요.", "Pixels. Recomenda-se 22-32; use valores maiores em telas sensíveis ao toque.", "Пиксели. Рекомендуется 22–32; на сенсорных экранах используйте большее значение.", "Piksel. 22-32 önerilir; dokunmatik ekranlarda daha büyük değer kullanın.", "Pixel. Khuyến nghị 22-32; dùng giá trị lớn hơn trên màn hình cảm ứng."],
  ["Pixels. Increase when the top is covered; use 0 for no extra gap.", "بالبكسل. زد القيمة عند حجب الأعلى؛ استخدم 0 دون فراغ إضافي.", "Pixel. Erhöhen, wenn der obere Bereich verdeckt ist; 0 für keinen zusätzlichen Abstand.", "Píxeles. Aumenta el valor si la parte superior queda cubierta; usa 0 sin espacio extra.", "Pixels. Augmentez si le haut est masqué ; utilisez 0 sans espace supplémentaire.", "Piksel. Tingkatkan bila bagian atas tertutup; gunakan 0 tanpa jarak tambahan.", "ピクセル。上部が隠れる場合は増やし、追加余白なしは 0 にします。", "픽셀. 상단이 가려지면 늘리고 추가 간격이 필요 없으면 0을 사용하세요.", "Pixels. Aumente quando o topo estiver coberto; use 0 sem espaço extra.", "Пиксели. Увеличьте, если верх перекрыт; 0 означает без дополнительного отступа.", "Piksel. Üst kısım kapalıysa artırın; ek boşluk için 0 kullanın.", "Pixel. Tăng khi phần trên bị che; dùng 0 nếu không cần khoảng trống."],
  ["Pixels. It is still clamped to the viewport on narrow screens.", "بالبكسل. ستظل القيمة مقيدة بإطار العرض على الشاشات الضيقة.", "Pixel. Auf schmalen Bildschirmen wird weiterhin an den sichtbaren Bereich angepasst.", "Píxeles. En pantallas estrechas seguirá limitado al área visible.", "Pixels. La valeur reste limitée à la zone visible sur les écrans étroits.", "Piksel. Pada layar sempit tetap dibatasi ke area tampilan.", "ピクセル。狭い画面では表示領域内に制限されます。", "픽셀. 좁은 화면에서는 여전히 화면 영역 안으로 제한됩니다.", "Pixels. Em telas estreitas, continuará limitado à área visível.", "Пиксели. На узких экранах значение всё равно ограничивается областью просмотра.", "Piksel. Dar ekranlarda görünüm alanına göre sınırlandırılır.", "Pixel. Trên màn hình hẹp, giá trị vẫn bị giới hạn trong vùng nhìn."],
  ["Raises PDF menu stacking and button hit areas to help inside review cards and embeds.", "يرفع ترتيب قائمة PDF ومساحات لمس الأزرار لتسهيل استخدامها داخل بطاقات المراجعة والتضمينات.", "Erhöht die Stapelreihenfolge des PDF-Menüs und die Trefferflächen der Schaltflächen in Review-Karten und Einbettungen.", "Eleva la capa del menú PDF y las áreas táctiles de los botones para facilitar su uso en tarjetas y contenidos incrustados.", "Augmente le niveau du menu PDF et la zone cliquable des boutons dans les cartes de révision et contenus intégrés.", "Menaikkan lapisan menu PDF dan area sentuh tombol agar mudah digunakan di kartu ulasan dan sematan.", "レビューカードや埋め込み内で使いやすいよう、PDF メニューの重なり順とボタンのタップ領域を拡大します。", "검토 카드와 임베드에서 쓰기 쉽도록 PDF 메뉴의 레이어와 버튼 터치 영역을 높입니다.", "Eleva a camada do menu PDF e as áreas de toque dos botões para uso em cartões e conteúdos incorporados.", "Повышает слой меню PDF и область нажатия кнопок для работы в карточках и встроенных представлениях.", "İnceleme kartları ve gömmelerde kullanım için PDF menü katmanını ve düğme dokunma alanlarını büyütür.", "Tăng lớp hiển thị menu PDF và vùng chạm nút để dễ dùng trong thẻ xem xét và nội dung nhúng."],
  ["Reorder pages", "إعادة ترتيب الصفحات", "Seiten neu anordnen", "Reordenar páginas", "Réordonner les pages", "Susun ulang halaman", "ページを並べ替える", "페이지 재정렬", "Reordenar páginas", "Изменить порядок страниц", "Sayfaları yeniden sırala", "Sắp xếp lại trang"],
  ["Revert", "استعادة", "Wiederherstellen", "Revertir", "Restaurer", "Kembalikan", "元に戻す", "되돌리기", "Reverter", "Восстановить", "Geri al", "Khôi phục"],
  ["Revert last PDF rewrite", "استعادة آخر إعادة كتابة لـ PDF", "Letzte PDF-Neuschreibung rückgängig machen", "Revertir la última reescritura del PDF", "Annuler la dernière réécriture du PDF", "Kembalikan penulisan ulang PDF terakhir", "直前の PDF 書き換えを元に戻す", "마지막 PDF 다시 쓰기 되돌리기", "Reverter a última regravação do PDF", "Отменить последнюю перезапись PDF", "Son PDF yeniden yazımını geri al", "Hoàn tác lần ghi lại PDF gần nhất"],
  ["Revert to the state before the last PDF rewrite? The current PDF file and editable annotations will be restored from backup.", "الاستعادة إلى الحالة قبل آخر إعادة كتابة لـ PDF؟ سيتم استرجاع ملف PDF الحالي والتعليقات القابلة للتحرير من النسخة الاحتياطية.", "Zum Zustand vor der letzten PDF-Neuschreibung zurückkehren? PDF und bearbeitbare Anmerkungen werden aus der Sicherung wiederhergestellt.", "¿Volver al estado anterior a la última reescritura? El PDF y las anotaciones editables se restaurarán desde la copia de seguridad.", "Revenir à l'état précédant la dernière réécriture ? Le PDF et les annotations modifiables seront restaurés depuis la sauvegarde.", "Kembali ke keadaan sebelum penulisan ulang PDF terakhir? PDF dan anotasi yang dapat diedit akan dipulihkan dari cadangan.", "直前の PDF 書き換え前に戻しますか？現在の PDF と編集可能な注釈をバックアップから復元します。", "마지막 PDF 다시 쓰기 전 상태로 돌아갈까요? 현재 PDF와 편집 가능한 주석을 백업에서 복원합니다.", "Voltar ao estado anterior à última regravação? O PDF e as anotações editáveis serão restaurados do backup.", "Вернуться к состоянию до последней перезаписи PDF? PDF и редактируемые аннотации будут восстановлены из резервной копии.", "Son PDF yeniden yazımından önceki duruma dönülsün mü? PDF ve düzenlenebilir notlar yedekten geri yüklenir.", "Khôi phục về trạng thái trước lần ghi lại PDF gần nhất? PDF hiện tại và chú thích có thể chỉnh sửa sẽ được phục hồi từ bản sao lưu."],
  ["Reverted the last PDF rewrite.", "تمت استعادة آخر إعادة كتابة لـ PDF.", "Letzte PDF-Neuschreibung wurde rückgängig gemacht.", "Se revirtió la última reescritura del PDF.", "La dernière réécriture du PDF a été annulée.", "Penulisan ulang PDF terakhir dikembalikan.", "直前の PDF 書き換えを元に戻しました。", "마지막 PDF 다시 쓰기를 되돌렸습니다.", "A última regravação do PDF foi revertida.", "Последняя перезапись PDF отменена.", "Son PDF yeniden yazımı geri alındı.", "Đã hoàn tác lần ghi lại PDF gần nhất."],
  ["Right", "يمين", "Rechts", "Derecha", "Droite", "Kanan", "右", "오른쪽", "Direita", "Справа", "Sağ", "Phải"],
  ["Save", "حفظ", "Speichern", "Guardar", "Enregistrer", "Simpan", "保存", "저장", "Salvar", "Сохранить", "Kaydet", "Lưu"],
  ["Selected pages cropped", "تم قص الصفحات المحددة", "Ausgewählte Seiten zugeschnitten", "Páginas seleccionadas recortadas", "Pages sélectionnées rognées", "Halaman terpilih dipangkas", "選択ページを切り抜きました", "선택한 페이지를 잘랐습니다", "Páginas selecionadas recortadas", "Выбранные страницы обрезаны", "Seçili sayfalar kırpıldı", "Đã cắt các trang đã chọn"],
  ["Selected pages rotated", "تم تدوير الصفحات المحددة", "Ausgewählte Seiten gedreht", "Páginas seleccionadas rotadas", "Pages sélectionnées pivotées", "Halaman terpilih diputar", "選択ページを回転しました", "선택한 페이지를 회전했습니다", "Páginas selecionadas giradas", "Выбранные страницы повёрнуты", "Seçili sayfalar döndürüldü", "Đã xoay các trang đã chọn"],
  ["Selection", "تحديد", "Auswahl", "Selección", "Sélection", "Pilihan", "選択", "선택", "Seleção", "Выделение", "Seçim", "Lựa chọn"],
  ["Selection and touch", "التحديد واللمس", "Auswahl und Touch", "Selección y toque", "Sélection et toucher", "Pilihan dan sentuh", "選択とタッチ", "선택 및 터치", "Seleção e toque", "Выделение и касание", "Seçim ve dokunma", "Lựa chọn và cảm ứng"],
  ["Send to back", "إرسال إلى الخلف", "In den Hintergrund", "Enviar al fondo", "Mettre à l'arrière-plan", "Kirim ke belakang", "最背面へ", "맨 뒤로", "Enviar para trás", "На задний план", "En arkaya gönder", "Đưa ra sau"],
  ["Show annotation toolbar when a PDF opens", "إظهار شريط التعليقات عند فتح PDF", "Anmerkungsleiste beim Öffnen eines PDFs anzeigen", "Mostrar la barra de anotaciones al abrir un PDF", "Afficher la barre d'annotations à l'ouverture d'un PDF", "Tampilkan bilah anotasi saat PDF dibuka", "PDF を開いたときに注釈ツールバーを表示", "PDF를 열 때 주석 도구 모음 표시", "Mostrar barra de anotações ao abrir um PDF", "Показывать панель аннотаций при открытии PDF", "PDF açıldığında not araç çubuğunu göster", "Hiện thanh chú thích khi mở PDF"],
  ["Show page navigator", "إظهار متصفح الصفحات", "Seitennavigator anzeigen", "Mostrar navegador de páginas", "Afficher le navigateur de pages", "Tampilkan navigator halaman", "ページナビゲーターを表示", "페이지 탐색기 표시", "Mostrar navegador de páginas", "Показывать навигатор страниц", "Sayfa gezginini göster", "Hiện trình điều hướng trang"],
  ["Source PDF", "ملف PDF المصدر", "Quell-PDF", "PDF de origen", "PDF source", "PDF sumber", "元の PDF", "원본 PDF", "PDF de origem", "Исходный PDF", "Kaynak PDF", "PDF nguồn"],
  ["Support the author", "دعم المؤلف", "Autor unterstützen", "Apoyar al autor", "Soutenir l'auteur", "Dukung pembuat", "作者を支援", "개발자 후원", "Apoiar o autor", "Поддержать автора", "Yazarı destekle", "Ủng hộ tác giả"],
  ["Text is ready to copy.", "النص جاهز للنسخ.", "Text kann kopiert werden.", "El texto está listo para copiar.", "Le texte est prêt à être copié.", "Teks siap disalin.", "テキストをコピーできます。", "텍스트를 복사할 수 있습니다.", "O texto está pronto para copiar.", "Текст готов к копированию.", "Metin kopyalanmaya hazır.", "Văn bản đã sẵn sàng để sao chép."],
  ["The rewrite backup does not match the current PDF.", "نسخة إعادة الكتابة الاحتياطية لا تطابق ملف PDF الحالي.", "Die Sicherung passt nicht zum aktuellen PDF.", "La copia de seguridad no coincide con el PDF actual.", "La sauvegarde ne correspond pas au PDF actuel.", "Cadangan penulisan ulang tidak cocok dengan PDF saat ini.", "書き換えバックアップが現在の PDF と一致しません。", "다시 쓰기 백업이 현재 PDF와 일치하지 않습니다.", "O backup não corresponde ao PDF atual.", "Резервная копия не соответствует текущему PDF.", "Yeniden yazma yedeği mevcut PDF ile eşleşmiyor.", "Bản sao lưu không khớp với PDF hiện tại."],
  ["Toggle PDF annotation", "تبديل تعليقات PDF", "PDF-Anmerkung umschalten", "Alternar anotación PDF", "Activer/désactiver l'annotation PDF", "Alihkan anotasi PDF", "PDF 注釈を切り替え", "PDF 주석 전환", "Alternar anotação PDF", "Переключить аннотации PDF", "PDF notunu aç/kapat", "Bật/tắt chú thích PDF"],
  ["Toolbar", "شريط الأدوات", "Werkzeugleiste", "Barra de herramientas", "Barre d'outils", "Bilah alat", "ツールバー", "도구 모음", "Barra de ferramentas", "Панель инструментов", "Araç çubuğu", "Thanh công cụ"],
  ["Toolbar button size", "حجم أزرار شريط الأدوات", "Größe der Werkzeugleisten-Schaltflächen", "Tamaño de botones de la barra", "Taille des boutons de la barre", "Ukuran tombol bilah alat", "ツールバーボタンのサイズ", "도구 모음 버튼 크기", "Tamanho dos botões da barra", "Размер кнопок панели", "Araç çubuğu düğme boyutu", "Kích thước nút thanh công cụ"],
  ["Toolbar max width", "أقصى عرض لشريط الأدوات", "Maximale Breite der Werkzeugleiste", "Ancho máximo de la barra", "Largeur maximale de la barre", "Lebar maksimum bilah alat", "ツールバーの最大幅", "도구 모음 최대 너비", "Largura máxima da barra", "Максимальная ширина панели", "Araç çubuğu azami genişliği", "Chiều rộng tối đa thanh công cụ"],
  ["Toolbar top offset", "إزاحة شريط الأدوات من الأعلى", "Oberer Abstand der Werkzeugleiste", "Desplazamiento superior de la barra", "Décalage supérieur de la barre", "Jarak atas bilah alat", "ツールバーの上部オフセット", "도구 모음 상단 오프셋", "Deslocamento superior da barra", "Отступ панели сверху", "Araç çubuğu üst uzaklığı", "Độ lệch trên của thanh công cụ"],
  ["Top", "أعلى", "Oben", "Arriba", "Haut", "Atas", "上", "위", "Superior", "Сверху", "Üst", "Trên"],
  ["Useful when most PDFs are annotated with Pdftion; the pen button still works when disabled.", "مفيد عند التعليق على معظم ملفات PDF باستخدام Pdftion؛ يظل زر القلم يعمل عند التعطيل.", "Nützlich, wenn die meisten PDFs mit Pdftion annotiert werden; die Stift-Schaltfläche funktioniert auch bei deaktivierter Option.", "Útil si la mayoría de los PDF se anotan con Pdftion; el botón del lápiz sigue funcionando al desactivarlo.", "Utile si la plupart des PDF sont annotés avec Pdftion ; le bouton stylo reste disponible lorsque l'option est désactivée.", "Berguna bila sebagian besar PDF dianotasi dengan Pdftion; tombol pena tetap berfungsi saat dinonaktifkan.", "多くの PDF を Pdftion で注釈する場合に便利です。無効でもペンボタンは使用できます。", "대부분의 PDF를 Pdftion으로 주석 처리할 때 유용합니다. 꺼도 펜 버튼은 작동합니다.", "Útil quando a maioria dos PDFs é anotada com Pdftion; o botão de caneta continua funcionando quando desativado.", "Полезно, если большинство PDF размечаются в Pdftion; кнопка пера работает и при отключённой опции.", "PDF'lerin çoğu Pdftion ile notlanıyorsa kullanışlıdır; devre dışıyken de kalem düğmesi çalışır.", "Hữu ích khi phần lớn PDF được chú thích bằng Pdftion; nút bút vẫn hoạt động khi tắt."],
  ["When enabled, highlight/copy actions follow the selected text; disable to use the older edge placement.", "عند التفعيل تتبع إجراءات التمييز والنسخ النص المحدد؛ عطله لاستخدام موضع الحافة القديم.", "Wenn aktiviert, folgen Markieren/Kopieren dem ausgewählten Text; deaktivieren für die frühere Randposition.", "Al activarlo, resaltar/copiar sigue el texto seleccionado; desactívalo para usar la posición anterior en el borde.", "Lorsque cette option est activée, surligner/copier suit le texte sélectionné ; désactivez-la pour utiliser l'ancien placement au bord.", "Saat aktif, tindakan sorot/salin mengikuti teks terpilih; nonaktifkan untuk posisi tepi lama.", "有効にするとハイライト/コピー操作が選択テキストに追従します。以前の端配置を使うには無効にします。", "활성화하면 강조/복사 작업이 선택한 텍스트를 따릅니다. 이전 가장자리 배치를 쓰려면 끄세요.", "Quando ativado, destacar/copiar acompanha o texto selecionado; desative para usar o posicionamento antigo na borda.", "Если включено, действия выделения/копирования следуют за выбранным текстом; отключите для прежнего размещения у края.", "Etkinleştirildiğinde vurgulama/kopyalama seçili metni izler; eski kenar yerleşimi için kapatın.", "Khi bật, thao tác tô sáng/sao chép đi theo văn bản đã chọn; tắt để dùng vị trí cạnh cũ."],
  ["Default", "افتراضي", "Standard", "Predeterminado", "Par défaut", "Bawaan", "既定", "기본값", "Padrão", "По умолчанию", "Varsayılan", "Mặc định"],
  ["Serif CJK", "خط CJK مزخرف", "CJK-Serifenschrift", "Serif CJK", "Serif CJK", "Serif CJK", "明朝体 CJK", "CJK 명조", "Serifa CJK", "CJK с засечками", "CJK serif", "Serif CJK"],
  ["Sans CJK", "خط CJK بدون زوائد", "CJK-Groteskschrift", "Sans CJK", "Sans CJK", "Sans CJK", "ゴシック体 CJK", "CJK 고딕", "Sem serifa CJK", "CJK без засечек", "CJK sans", "Sans CJK"],
  ["Mono", "أحادي المسافة", "Dicktengleich", "Monoespaciada", "Chasse fixe", "Monospace", "等幅", "고정폭", "Monoespaçada", "Моноширинный", "Eş aralıklı", "Đơn cách"],
  ["Serif", "مزخرف", "Serifenschrift", "Serif", "Serif", "Serif", "セリフ", "명조", "Serifa", "С засечками", "Serif", "Serif"]
];

export const PDFTION_EXTENDED_TRANSLATIONS: Readonly<Record<ExtendedLocale, Readonly<Record<string, string>>>> = (() => {
  const translations = Object.fromEntries(
    EXTENDED_LOCALES.map((locale) => [locale, {} as Record<string, string>])
  ) as Record<ExtendedLocale, Record<string, string>>;
  for (const row of STATIC_TRANSLATION_ROWS) {
    EXTENDED_LOCALES.forEach((locale, index) => {
      const value = row[index + 1];
      if (value) {
        translations[locale][row[0]] = value;
      }
    });
  }
  return translations;
})();

const DYNAMIC_TRANSLATION_ROWS: TranslationRow[] = [
  ["Page {page} comment", "تعليق الصفحة {page}", "Kommentar auf Seite {page}", "Comentario de la página {page}", "Commentaire de la page {page}", "Komentar halaman {page}", "{page} ページのコメント", "{page}페이지 댓글", "Comentário da página {page}", "Комментарий на странице {page}", "Sayfa {page} yorumu", "Bình luận trang {page}"],
  ["Page {page}", "الصفحة {page}", "Seite {page}", "Página {page}", "Page {page}", "Halaman {page}", "{page} ページ", "{page}페이지", "Página {page}", "Страница {page}", "Sayfa {page}", "Trang {page}"],
  ["Page {page}, {count} elements", "الصفحة {page}، {count} عناصر", "Seite {page}, {count} Elemente", "Página {page}, {count} elementos", "Page {page}, {count} éléments", "Halaman {page}, {count} elemen", "{page} ページ、{count} 要素", "{page}페이지, 요소 {count}개", "Página {page}, {count} elementos", "Страница {page}, элементов: {count}", "Sayfa {page}, {count} öğe", "Trang {page}, {count} phần tử"],
  ["P {pages} | ink {strokes} | text {texts} | img {images} | cover {covers}", "ص {pages} | حبر {strokes} | نص {texts} | صور {images} | تغطية {covers}", "S {pages} | Tinte {strokes} | Text {texts} | Bild {images} | Abdeckung {covers}", "P {pages} | tinta {strokes} | texto {texts} | img {images} | cubierta {covers}", "P {pages} | encre {strokes} | texte {texts} | img {images} | cache {covers}", "H {pages} | tinta {strokes} | teks {texts} | gambar {images} | penutup {covers}", "P {pages} | インク {strokes} | テキスト {texts} | 画像 {images} | 覆い {covers}", "P {pages} | 잉크 {strokes} | 텍스트 {texts} | 이미지 {images} | 가림 {covers}", "P {pages} | tinta {strokes} | texto {texts} | img {images} | cobertura {covers}", "С {pages} | штрихи {strokes} | текст {texts} | изобр. {images} | закрытия {covers}", "S {pages} | mürekkep {strokes} | metin {texts} | görsel {images} | kapak {covers}", "T {pages} | nét {strokes} | chữ {texts} | ảnh {images} | che {covers}"],
  ["Enter a new page order, for example 3,1,2 or 1-3,5. Current pages: {count}.", "أدخل ترتيب صفحات جديدا، مثل 3,1,2 أو 1-3,5. الصفحات الحالية: {count}.", "Neue Seitenreihenfolge eingeben, z. B. 3,1,2 oder 1-3,5. Aktuelle Seiten: {count}.", "Introduce un nuevo orden, por ejemplo 3,1,2 o 1-3,5. Páginas actuales: {count}.", "Saisissez un nouvel ordre, par exemple 3,1,2 ou 1-3,5. Pages actuelles : {count}.", "Masukkan urutan baru, misalnya 3,1,2 atau 1-3,5. Halaman saat ini: {count}.", "新しいページ順を入力します。例: 3,1,2 または 1-3,5。現在のページ数: {count}。", "새 페이지 순서를 입력하세요. 예: 3,1,2 또는 1-3,5. 현재 페이지: {count}.", "Digite uma nova ordem, por exemplo 3,1,2 ou 1-3,5. Páginas atuais: {count}.", "Введите новый порядок, например 3,1,2 или 1-3,5. Текущее число страниц: {count}.", "Yeni sayfa sırası girin; örneğin 3,1,2 veya 1-3,5. Mevcut sayfalar: {count}.", "Nhập thứ tự trang mới, ví dụ 3,1,2 hoặc 1-3,5. Số trang hiện tại: {count}."],
  ["Delete {count} pages? This will modify the current PDF.", "حذف {count} صفحات؟ سيؤدي ذلك إلى تعديل PDF الحالي.", "{count} Seiten löschen? Dadurch wird das aktuelle PDF geändert.", "¿Eliminar {count} páginas? Se modificará el PDF actual.", "Supprimer {count} pages ? Le PDF actuel sera modifié.", "Hapus {count} halaman? Ini akan mengubah PDF saat ini.", "{count} ページを削除しますか？現在の PDF が変更されます。", "{count}개 페이지를 삭제할까요? 현재 PDF가 수정됩니다.", "Excluir {count} páginas? Isso modificará o PDF atual.", "Удалить {count} страниц? Текущий PDF будет изменён.", "{count} sayfa silinsin mi? Mevcut PDF değiştirilecek.", "Xóa {count} trang? PDF hiện tại sẽ bị sửa đổi."],
  ["Imported and merged {name}", "تم استيراد ودمج {name}", "{name} importiert und zusammengeführt", "{name} importado y combinado", "{name} importé et fusionné", "{name} diimpor dan digabung", "{name} を取り込んで結合しました", "{name} 가져오기 및 병합 완료", "{name} importado e mesclado", "{name} импортирован и объединён", "{name} içe aktarıldı ve birleştirildi", "Đã nhập và hợp nhất {name}"],
  ["Saved into {name}.", "تم الحفظ في {name}.", "In {name} gespeichert.", "Guardado en {name}.", "Enregistré dans {name}.", "Disimpan ke {name}.", "{name} に保存しました。", "{name}에 저장했습니다.", "Salvo em {name}.", "Сохранено в {name}.", "{name} içine kaydedildi.", "Đã lưu vào {name}."],
  ["Exported converted documents: {paths}", "تم تصدير المستندات المحولة: {paths}", "Konvertierte Dokumente exportiert: {paths}", "Documentos convertidos exportados: {paths}", "Documents convertis exportés : {paths}", "Dokumen hasil konversi diekspor: {paths}", "変換文書を出力しました: {paths}", "변환 문서 내보내기 완료: {paths}", "Documentos convertidos exportados: {paths}", "Преобразованные документы экспортированы: {paths}", "Dönüştürülen belgeler dışa aktarıldı: {paths}", "Đã xuất tài liệu chuyển đổi: {paths}"],
  ["Converted{opened} editable MD with native images and NoteDraw ink: {path}", "تم التحويل{opened} إلى MD قابل للتحرير مع صور أصلية وحبر NoteDraw: {path}", "{opened}In bearbeitbares MD mit nativen Bildern und NoteDraw-Tinte konvertiert: {path}", "Convertido{opened} a MD editable con imágenes nativas y tinta NoteDraw: {path}", "Converti{opened} en MD modifiable avec images natives et encre NoteDraw : {path}", "Dikonversi{opened} menjadi MD yang dapat diedit dengan gambar asli dan tinta NoteDraw: {path}", "ネイティブ画像と NoteDraw インクを含む編集可能な MD に変換{opened}: {path}", "기본 이미지와 NoteDraw 잉크가 있는 편집 가능한 MD로 변환{opened}: {path}", "Convertido{opened} em MD editável com imagens nativas e tinta NoteDraw: {path}", "Преобразовано{opened} в редактируемый MD с исходными изображениями и штрихами NoteDraw: {path}", "Yerel görüntüler ve NoteDraw mürekkebi içeren düzenlenebilir MD'ye dönüştürüldü{opened}: {path}", "Đã chuyển đổi{opened} sang MD có thể chỉnh sửa với ảnh gốc và nét NoteDraw: {path}"],
  ["Converted{opened} MD with native image references: {path}", "تم التحويل{opened} إلى MD مع مراجع صور أصلية: {path}", "{opened}In MD mit nativen Bildverweisen konvertiert: {path}", "Convertido{opened} a MD con referencias de imágenes nativas: {path}", "Converti{opened} en MD avec références d'images natives : {path}", "Dikonversi{opened} menjadi MD dengan referensi gambar asli: {path}", "ネイティブ画像参照を含む MD に変換{opened}: {path}", "기본 이미지 참조가 있는 MD로 변환{opened}: {path}", "Convertido{opened} em MD com referências de imagens nativas: {path}", "Преобразовано{opened} в MD со ссылками на исходные изображения: {path}", "Yerel görüntü başvuruları içeren MD'ye dönüştürüldü{opened}: {path}", "Đã chuyển đổi{opened} sang MD có tham chiếu ảnh gốc: {path}"],
  ["Converted{opened} {format}: {path}", "تم التحويل{opened} إلى {format}: {path}", "{opened}In {format} konvertiert: {path}", "Convertido{opened} a {format}: {path}", "Converti{opened} en {format} : {path}", "Dikonversi{opened} menjadi {format}: {path}", "{format} に変換{opened}: {path}", "{format}(으)로 변환{opened}: {path}", "Convertido{opened} em {format}: {path}", "Преобразовано{opened} в {format}: {path}", "{format} biçimine dönüştürüldü{opened}: {path}", "Đã chuyển đổi{opened} sang {format}: {path}"],
  ["{format} conversion failed: {message}", "فشل تحويل {format}: {message}", "{format}-Konvertierung fehlgeschlagen: {message}", "Falló la conversión {format}: {message}", "Échec de la conversion {format} : {message}", "Konversi {format} gagal: {message}", "{format} 変換に失敗しました: {message}", "{format} 변환 실패: {message}", "Falha na conversão {format}: {message}", "Ошибка преобразования {format}: {message}", "{format} dönüştürme başarısız: {message}", "Chuyển đổi {format} thất bại: {message}"],
  ["Exported and opened: {path}", "تم التصدير والفتح: {path}", "Exportiert und geöffnet: {path}", "Exportado y abierto: {path}", "Exporté et ouvert : {path}", "Diekspor dan dibuka: {path}", "出力して開きました: {path}", "내보내고 열었습니다: {path}", "Exportado e aberto: {path}", "Экспортировано и открыто: {path}", "Dışa aktarıldı ve açıldı: {path}", "Đã xuất và mở: {path}"],
  ["Exported and shared: {path}", "تم التصدير والمشاركة: {path}", "Exportiert und geteilt: {path}", "Exportado y compartido: {path}", "Exporté et partagé : {path}", "Diekspor dan dibagikan: {path}", "出力して共有しました: {path}", "내보내고 공유했습니다: {path}", "Exportado e compartilhado: {path}", "Экспортировано и отправлено: {path}", "Dışa aktarıldı ve paylaşıldı: {path}", "Đã xuất và chia sẻ: {path}"],
  ["Exported: {path}", "تم التصدير: {path}", "Exportiert: {path}", "Exportado: {path}", "Exporté : {path}", "Diekspor: {path}", "出力しました: {path}", "내보냈습니다: {path}", "Exportado: {path}", "Экспортировано: {path}", "Dışa aktarıldı: {path}", "Đã xuất: {path}"],
  ["Flattened covers on {count} pages", "تم تسطيح مناطق التغطية في {count} صفحات", "Abdeckungen auf {count} Seiten reduziert", "Cubiertas acopladas en {count} páginas", "Caches aplatis sur {count} pages", "Penutup diratakan pada {count} halaman", "{count} ページの覆いを統合しました", "{count}개 페이지의 가림 영역을 병합했습니다", "Coberturas achatadas em {count} páginas", "Закрывающие области сведены на {count} страницах", "{count} sayfadaki kapaklar düzleştirildi", "Đã làm phẳng vùng che trên {count} trang"]
];

const DYNAMIC_TRANSLATIONS: Readonly<Record<ExtendedLocale, Readonly<Record<string, string>>>> = (() => {
  const translations = Object.fromEntries(
    EXTENDED_LOCALES.map((locale) => [locale, {} as Record<string, string>])
  ) as Record<ExtendedLocale, Record<string, string>>;
  for (const row of DYNAMIC_TRANSLATION_ROWS) {
    EXTENDED_LOCALES.forEach((locale, index) => {
      const value = row[index + 1];
      if (value) {
        translations[locale][row[0]] = value;
      }
    });
  }
  return translations;
})();

interface DynamicTranslationMatch {
  key: string;
  values: Record<string, string>;
}

export function getExtendedPdftionTranslation(locale: string, english: string): string | undefined {
  if (!EXTENDED_LOCALES.includes(locale as ExtendedLocale)) {
    return undefined;
  }
  const typedLocale = locale as ExtendedLocale;
  const direct = PDFTION_EXTENDED_TRANSLATIONS[typedLocale][english];
  if (direct) {
    return direct;
  }
  const match = matchDynamicTranslation(english);
  const template = match ? DYNAMIC_TRANSLATIONS[typedLocale][match.key] : undefined;
  if (!match || !template) {
    return undefined;
  }
  const opened = match.values.opened === " and opened"
    ? OPENED_TRANSLATIONS[typedLocale]
    : "";
  return formatTranslation(template, { ...match.values, opened });
}

const OPENED_TRANSLATIONS: Record<ExtendedLocale, string> = {
  ar: " وفتحه",
  de: "Geöffnet und ",
  es: " y abierto",
  fr: " et ouvert",
  id: " dan dibuka",
  ja: "して開きました",
  ko: "하고 열었습니다",
  pt: " e aberto",
  ru: " и открыто",
  tr: " ve açıldı",
  vi: " và đã mở"
};

function matchDynamicTranslation(english: string): DynamicTranslationMatch | null {
  let match = english.match(/^Page (\d+) comment$/);
  if (match) return { key: "Page {page} comment", values: { page: match[1] } };
  match = english.match(/^Page (\d+), (\d+) elements$/);
  if (match) return { key: "Page {page}, {count} elements", values: { count: match[2], page: match[1] } };
  match = english.match(/^Page (\d+)$/);
  if (match) return { key: "Page {page}", values: { page: match[1] } };
  match = english.match(/^P (\d+) \| ink (\d+) \| text (\d+) \| img (\d+) \| cover (\d+)$/);
  if (match) return { key: "P {pages} | ink {strokes} | text {texts} | img {images} | cover {covers}", values: { covers: match[5], images: match[4], pages: match[1], strokes: match[2], texts: match[3] } };
  match = english.match(/^Enter a new page order, for example 3,1,2 or 1-3,5\. Current pages: (\d+)\.$/);
  if (match) return { key: "Enter a new page order, for example 3,1,2 or 1-3,5. Current pages: {count}.", values: { count: match[1] } };
  match = english.match(/^Delete (\d+) pages\? This will modify the current PDF\.$/);
  if (match) return { key: "Delete {count} pages? This will modify the current PDF.", values: { count: match[1] } };
  match = english.match(/^Imported and merged (.+)$/);
  if (match) return { key: "Imported and merged {name}", values: { name: match[1] } };
  match = english.match(/^Saved into (.+)\.$/);
  if (match) return { key: "Saved into {name}.", values: { name: match[1] } };
  match = english.match(/^Exported converted documents: (.+)$/);
  if (match) return { key: "Exported converted documents: {paths}", values: { paths: match[1] } };
  match = english.match(/^Converted( and opened)? editable MD with native images and NoteDraw ink: (.+)$/);
  if (match) return { key: "Converted{opened} editable MD with native images and NoteDraw ink: {path}", values: { opened: match[1] ?? "", path: match[2] } };
  match = english.match(/^Converted( and opened)? MD with native image references: (.+)$/);
  if (match) return { key: "Converted{opened} MD with native image references: {path}", values: { opened: match[1] ?? "", path: match[2] } };
  match = english.match(/^Converted( and opened)? (DOCX|PNG|PPTX|HTML): (.+)$/);
  if (match) return { key: "Converted{opened} {format}: {path}", values: { format: match[2], opened: match[1] ?? "", path: match[3] } };
  match = english.match(/^(PPTX|PDF) conversion failed: (.+)$/);
  if (match) return { key: "{format} conversion failed: {message}", values: { format: match[1], message: match[2] } };
  match = english.match(/^Exported and opened: (.+)$/);
  if (match) return { key: "Exported and opened: {path}", values: { path: match[1] } };
  match = english.match(/^Exported and shared: (.+)$/);
  if (match) return { key: "Exported and shared: {path}", values: { path: match[1] } };
  match = english.match(/^Exported: (.+)$/);
  if (match) return { key: "Exported: {path}", values: { path: match[1] } };
  match = english.match(/^Flattened covers on (\d+) pages$/);
  if (match) return { key: "Flattened covers on {count} pages", values: { count: match[1] } };
  return null;
}

function formatTranslation(template: string, values: Record<string, string>): string {
  return template.replace(/\{([a-z]+)\}/gi, (_match, key: string) => values[key] ?? "");
}
